/*
 * Copyright 2026 Turing Software LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by npt_protocol.py -- do not edit.
 *
 * Command structs and encode/decode for id3d10blob.
 */

#ifndef NPT_PROTOCOL_HOST_ID3D10BLOB_H
#define NPT_PROTOCOL_HOST_ID3D10BLOB_H

#include "npt_protocol_host_structs.h"
#include "npt_protocol_host_dispatch_types.h"

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wpointer-arith"

/*
 * ID3D10Blob::GetBufferPointer
 *
 * HAND-WRITTEN reply: the real ABI returns LPVOID, a host-process
 * pointer meaningless to the guest, so the codegen'd version of this
 * function correctly stubbed the call but never marshalled any bytes
 * back. See npt_protocol_guest_id3d10blob.h for the full explanation
 * and the matching guest-side rewrite. This dispatch now calls the
 * real _original (its return type is fixed to `void *` in
 * npt_protocol_host_dispatch_types.h -- it used to be declared `void`,
 * silently discarding the real pointer even when _original was called
 * directly), reads GetBufferSize bytes starting there, and encodes them
 * into the reply with the same array_count + blob_array primitives
 * D3D12_SHADER_BYTECODE uses guest->host, just mirrored here.
 */

struct npt_command_ID3D10Blob_GetBufferPointer {
    void *_self;
    void *ret;
};

static inline void
npt_decode_ID3D10Blob_GetBufferPointer_args_temp(struct npt_cs_decoder *dec,
                                                 struct npt_command_ID3D10Blob_GetBufferPointer *args)
{
    /* Decode input parameters from the wire */
    /* Allocate temp storage for output-only parameters */
}

static inline void
npt_replace_ID3D10Blob_GetBufferPointer_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D10Blob_GetBufferPointer *args)
{
}

static inline void
npt_encode_ID3D10Blob_GetBufferPointer_reply(struct npt_cs_encoder *enc,
                                             const struct npt_command_ID3D10Blob_GetBufferPointer *args,
                                             SIZE_T buf_size)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D10Blob,
                                 NPT_METHOD_ID3D10Blob_GetBufferPointer),
        .cmd_return = 0,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
    if (args->ret && buf_size) {
        npt_encode_array_count(enc, buf_size);
        npt_encode_blob_array(enc, args->ret, buf_size);
    } else {
        npt_encode_array_count(enc, 0);
    }
}

static inline void
npt_dispatch_ID3D10Blob_GetBufferPointer(struct npt_dispatch_context *ctx,
                                         uint32_t cmd_flags,
                                         uint64_t object_id)
{
    struct npt_command_ID3D10Blob_GetBufferPointer args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D10Blob_GetBufferPointer_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D10BLOB);
    if (!args._self) {
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D10Blob_GetBufferPointer_args_handle(ctx, &args);

    /* One or more non-_self object-typed arguments (direct params
     * and/or embedded struct fields) may have failed to resolve via
     * npt_cs_handle_lookup() above -- that failure already called
     * npt_cs_decoder_set_fatal() internally, mirroring the _self
     * check a few lines up.  Re-check here before touching _original
     * or any override: proceeding would call the real driver with a
     * NULL required pointer instead of cleanly aborting this command. */
    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    PFN_ID3D10Blob_GetBufferPointer _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D10Blob_GetBufferPointer, npt_com_vtable(args._self),
        NPT_VTBL_ID3D10Blob_GetBufferPointer);

    if (ctx->id3d10blob_dispatch_overrides && ctx->id3d10blob_dispatch_overrides->GetBufferPointer) {
        args.ret = ctx->id3d10blob_dispatch_overrides->GetBufferPointer(ctx, &args, _original);
    } else {
        args.ret = _original(args._self);
    }

    /* GetBufferSize is the same real interface's own accessor for the
     * length of the buffer args.ret points at -- always safe/cheap to
     * call again here regardless of override path. */
    PFN_ID3D10Blob_GetBufferSize _original_size = NPT_COM_VTBL_FUNC(
        PFN_ID3D10Blob_GetBufferSize, npt_com_vtable(args._self),
        NPT_VTBL_ID3D10Blob_GetBufferSize);
    SIZE_T buf_size = _original_size ? _original_size(args._self) : 0;

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D10Blob_GetBufferPointer_reply(ctx->encoder, &args, buf_size);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D10Blob::GetBufferSize
 */

struct npt_command_ID3D10Blob_GetBufferSize {
    void *_self;
    SIZE_T ret;
};

static inline void
npt_decode_ID3D10Blob_GetBufferSize_args_temp(struct npt_cs_decoder *dec,
                                              struct npt_command_ID3D10Blob_GetBufferSize *args)
{
    /* Decode input parameters from the wire */
    /* Allocate temp storage for output-only parameters */
}

static inline void
npt_replace_ID3D10Blob_GetBufferSize_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D10Blob_GetBufferSize *args)
{
}

static inline void
npt_encode_ID3D10Blob_GetBufferSize_reply(struct npt_cs_encoder *enc,
                                          const struct npt_command_ID3D10Blob_GetBufferSize *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D10Blob,
                                 NPT_METHOD_ID3D10Blob_GetBufferSize),
        .cmd_return = 0,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
    npt_encode_SIZE_T(enc, &args->ret);
}

static inline void
npt_dispatch_ID3D10Blob_GetBufferSize(struct npt_dispatch_context *ctx,
                                      uint32_t cmd_flags,
                                      uint64_t object_id)
{
    struct npt_command_ID3D10Blob_GetBufferSize args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D10Blob_GetBufferSize_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D10BLOB);
    if (!args._self) {
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D10Blob_GetBufferSize_args_handle(ctx, &args);

    /* One or more non-_self object-typed arguments (direct params
     * and/or embedded struct fields) may have failed to resolve via
     * npt_cs_handle_lookup() above -- that failure already called
     * npt_cs_decoder_set_fatal() internally, mirroring the _self
     * check a few lines up.  Re-check here before touching _original
     * or any override: proceeding would call the real driver with a
     * NULL required pointer instead of cleanly aborting this command. */
    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    PFN_ID3D10Blob_GetBufferSize _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D10Blob_GetBufferSize, npt_com_vtable(args._self),
        NPT_VTBL_ID3D10Blob_GetBufferSize);

    if (ctx->id3d10blob_dispatch_overrides && ctx->id3d10blob_dispatch_overrides->GetBufferSize) {
        args.ret = ctx->id3d10blob_dispatch_overrides->GetBufferSize(ctx, &args, _original);
    } else {
        args.ret = _original(args._self);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D10Blob_GetBufferSize_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}


#pragma GCC diagnostic pop

#endif /* NPT_PROTOCOL_HOST_ID3D10BLOB_H */
